export const podcastData = {
  allPodcasts: [
    {
      id: '1',
      title: 'Tech Talk Daily',
      episodes: '45 Episodes',
      duration: '1h 20 min',
      category: 'Technology',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '2',
      title: 'Health & Wellness Podcast',
      episodes: '30 Episodes',
      duration: '1h 15 min',
      category: 'Health',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '3',
      title: 'History Uncovered',
      episodes: '25 Episodes',
      duration: '2h 10 min',
      category: 'History',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '4',
      title: 'Startup Stories',
      episodes: '18 Episodes',
      duration: '50 min',
      category: 'Business',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '5',
      title: 'Fitness Focus',
      episodes: '60 Episodes',
      duration: '1h 40 min',
      category: 'Fitness',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '6',
      title: 'Mindset Mastery',
      episodes: '20 Episodes',
      duration: '1h 5 min',
      category: 'Motivation',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '7',
      title: 'Daily Tech Briefing',
      episodes: '55 Episodes',
      duration: '1h 25 min',
      category: 'Technology',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '8',
      title: 'Travel Diaries',
      episodes: '40 Episodes',
      duration: '1h 50 min',
      category: 'Travel',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '9',
      title: 'Cooking with Love',
      episodes: '32 Episodes',
      duration: '1h 10 min',
      category: 'Cooking',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '10',
      title: 'Music & Beats',
      episodes: '70 Episodes',
      duration: '1h 30 min',
      category: 'Music',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '11',
      title: 'Mindful Meditations',
      episodes: '15 Episodes',
      duration: '50 min',
      category: 'Meditation',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '12',
      title: 'Fashion Forward',
      episodes: '20 Episodes',
      duration: '1h 25 min',
      category: 'Fashion',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '13',
      title: 'The Science Hour',
      episodes: '45 Episodes',
      duration: '2h 10 min',
      category: 'Science',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '14',
      title: 'Entrepreneurial Edge',
      episodes: '22 Episodes',
      duration: '1h 45 min',
      category: 'Business',
      image: 'https://picsum.photos/275/125',
    },
    {
      id: '15',
      title: 'The Art of Design',
      episodes: '10 Episodes',
      duration: '1h 35 min',
      category: 'Design',
      image: 'https://picsum.photos/275/125',
    },
  ],
  myPlaylist: [
    {
      id: '1',
      title: 'The Daily Grind',
      episodes: '30 Episodes',
      duration: '1h 15 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '2',
      title: 'Wellness Weekly',
      episodes: '25 Episodes',
      duration: '1h 10 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '3',
      title: 'Startup Insights',
      episodes: '40 Episodes',
      duration: '1h 50 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '4',
      title: 'Creative Minds',
      episodes: '35 Episodes',
      duration: '1h 25 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '5',
      title: 'Exploring the Cosmos',
      episodes: '15 Episodes',
      duration: '2h 5 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '6',
      title: 'Mind Over Matter',
      episodes: '22 Episodes',
      duration: '1h 30 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '7',
      title: 'Fitness Fuel',
      episodes: '50 Episodes',
      duration: '2h 15 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '8',
      title: 'Music Therapy',
      episodes: '40 Episodes',
      duration: '1h 45 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '9',
      title: 'Cooking Corner',
      episodes: '25 Episodes',
      duration: '1h 20 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
    {
      id: '10',
      title: 'Mindfulness Moments',
      episodes: '18 Episodes',
      duration: '1h 10 min',
      thumbnail: 'https://picsum.photos/80/80',
    },
  ],
};
